name: Github to Docker Hub
on:
  push:
    branches: [ feature ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build docker image for client
      run: docker build -t trantbatey/react-test -f ./client/Dockerfile.dev ./client
    - name: run client test
      run: docker run -e CI=true trantbatey/react-test npm run test
    
  # .github/workflows/heroku-deploy.yml
  heroku-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
